import Curve from "@/components/Layout/Curve";
import Head from "next/head";
import { motion, useViewportScroll, useTransform } from "framer-motion";
import styles from "./style.module.scss";

export default function Work() {
  const { scrollYProgress } = useViewportScroll();
  const scale = useTransform(scrollYProgress, [0, 1], [0.2, 2]);

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Curve>
        {/* <h1>Work</h1> */}
        <div className={styles.maincontainer}>
          <div className={styles.wrapper}
          style={{
            
          }}
          >
            <motion.div
              className={styles.container}
              // style={{
              //   backgroundImage: "url(https://picsum.photos/200)",
              //   zIndex: 4,
              //   backgroundPosition: { scrollYProgress },
              //   //  clipPath: "inset(0px 0px 71.0959%)",
              // }}

              // style={{
              //   scale,
              // }}
            >
              <motion.div
                className={styles.item}
                style={{
                  scaleY: scrollYProgress,
                  // backgroundImage: "url(https://picsum.photos/201)",
                  // zIndex: 5,
                  //  backgroundPosition: {scrollYProgress},
                }}
              />
            </motion.div>
          </div>
        </div>
      </Curve>
    </>
  );
}
